all: 0 1 2 3 4 5 6 7 8 9

.PHONY: 0 1 2 3 4 5 6 7 8 9

database:
	createdb database
	psql -U maganand -d database -a -f ../materials/model.sql

0: day00_ex00.sql
	psql -U maganand -d database -a -f day00_ex00.sql

1: day00_ex01.sql
	psql -U maganand -d database -a -f day00_ex01.sql

2: day00_ex02.sql
	psql -U maganand -d database -a -f day00_ex02.sql

3: day00_ex03.sql
	psql -U maganand -d database -a -f day00_ex03.sql

4: day00_ex04.sql
	psql -U maganand -d database -a -f day00_ex04.sql

5: day00_ex05.sql
	psql -U maganand -d database -a -f day00_ex05.sql

6: day00_ex06.sql
	psql -U maganand -d database -a -f day00_ex06.sql

7: day00_ex07.sql
	psql -U maganand -d database -a -f day00_ex07.sql

8: day00_ex08.sql
	psql -U maganand -d database -a -f day00_ex08.sql

9: day00_ex09.sql
	psql -U maganand -d database -a -f day00_ex09.sql